logging:
  config: classpath:${LOGBACK:logback.xml}
  level:
    root: info
    com:
      dionext: debug
spring:
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin}

web-config:
    siteStaticStoragePath: "file:/mnt/disk2/sites/dioportal/input"
    siteStoragePaths:
      - "file:/mnt/disk2/sites/dioportal/input"
    siteInternalStoragePaths:
      - "file:/mnt/disk2/sites/dioportal/mediainfo"
