#management:
 # endpoints:
  #  web:
   #   base-path: /api/actuator/
management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  health:
    defaults.enabled: false
    probes.enabled: true
    ping.enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      base-path: /dioportal/actuator/
      exposure:
        include: '*'
  endpoint:
    loggers:
      enabled: true
    health:
      enabled: true
      show-details: always
      show-components: always
      #group:
      #  liveness.include: ["*"]
      #  readiness.include: ["*"]
    info.enabled: true
    mappings.enabled: true
    prometheus.enabled: true
    flyway.enabled: true
  metrics:
    #export:
    # elastic:
    #  host: https://elastic.example.com:8086:
    # ??????? ?? ??? ???????? ??????? ?? ??????? ? ?????????? ????????
    # ? ??????? ?????????? (??????? http.server.requests)
    web.server.request.autotime:
      enabled: true
      percentiles-histogram: true
    web.client.request.autotime:
      percentiles-histogram: true
    tags:
      app: ${info.name}

info:
  #name: '@project.name@' #not working
  #description: '@project.description@' #not working
  name: 'dioportal'
  description: 'Dionext.com main site'
  version: '@project.version@'
  time: '@maven.build.timestamp@'
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
server:
  port: 8082
  shutdown:
    graceful # see also spring.lifecycle.timeout-per-shutdown-phase=1m
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
    log-startup-info: true
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  thymeleaf:
    check-template-location: false # to prevent warning
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin}

keycloak:
  enabled: false
  #boot:
  #  admin:
  #    client:
  #      url: http://localhost:8086
  #      instance:
  #        name: dio-ms-app
  #        service-host-type: ip
  #      enabled: true
logging:
  level:
    com:
      zaxxer:
        hikari: OFF # suppress errors in log when DatabaseStartupValidator trying to connect to database
    #org.springframework.security: TRACE # for trace spring  security

# Web-sites config
web-config:
  website:
    staticPrefixes:
      - "images"
      - "media"
    siteLangs: "en"
    siteLangInPath: true
    siteDomain: "dionext.com"
    siteProtocol: "https"
    siteStaticStoragePath: "file:/mnt/sites/dioportal/input"
    siteStoragePaths:
      - "file:/mnt/sites/dioportal/input"
    siteInternalStoragePaths:
      - "file:/mnt/sites/dioportal/mediainfo"
    createMetaOg: true
    createMetaForIcons: true
    useExternalUrlForImages: false
    keywords:
      key: "dioportal.site.keywords"
    description:
      key: "dioportal.site.description"
    siteTitle:
      key: "dioportal.site.title"
    googleTagID: "G-GD83XCL778"
    nav:
      - item:
        key: "dioportal.menu.home"
        url: "index.htm"
      - item:
        name: "Architecture"
        url: "index.htm#architecture"
        subitems:
          - item:
            name: "Principles and rules"
            url: "software-development-principles.htm"
          - item:
            name: "Microservices"
            url: "architecture-microservices.htm"
      - item:
        name: "Development"
        url: "index.htm#development"
        subitems:
          - item:
            name: "Tools"
            url: "index.htm#tools"
          - item:
            name: "Java"
            url: "index.htm#java"
          - item:
            name: "Spring"
            url: "index.htm#spring"
          - item:
            name: "Web"
            url: "index.htm#web"
          - item:
            name: "Texts and Media"
            url: "index.htm#texts"
          - item:
            name: "Data"
            url: "index.htm#data"
          - item:
            name: "Integration"
            url: "integration-technologies.htm"
          - item:
            name: "Testing"
            url: "testing-and-debugging.htm"
          - item:
            name: "Profiling"
            url: "java-profiling.htm"
      - item:
        name: "Devops"
        url: "index.htm#deployment"
        subitems:
          - item:
            name: "Devops"
            url: "devops.htm"
          - item:
            name: "Remote delivery"
            url: "devops-remote-operations.htm"
          - item:
            name: "Linux"
            url: "os-linux.htm"
          - item:
            name: "Git"
            url: "devops-git.htm"
          - item:
            name: "Runtime"
            url: "index.htm#runtime"
      - item:
        name: "Maintenance"
        url: "index.htm#maintenance."
        subitems:
          - item:
            name: "Logging"
            url: "devops-logging.htm"
          - item:
            name: "Monitoring"
            url: "devops-monitoring.htm"
      #- item:
      #  name: "Free products"
      #  subitems:
      #    - item:
      #      name: "Site starter"
      #      url: "lib-site-spring-starter.htm"
      - item:
        key: "dioportal.menu.about.project"
        url: "about.htm"

